#! /bin/ksh

# @(#) $Header: /Users/thomas/direwolf-libax25-agwpe/wampes-import/wampes-cvs/wampes/tools/fixnetrc,v 1.7 1996/08/11 18:17:09 deyke Exp $

empty=/tmp/tmp$$

rm -f /tmp/iprt.* $empty

echo ' ' > $empty

makeiprt || exit 1

for i in net.rc.*; do
	file=${i#net.rc.}
	if [[ -f /tmp/iprt.$file ]]; then
		ex - net.rc.$file <<EOF
		%g/^route add/d
		r $empty
		r /tmp/iprt.$file
		r $empty
		x
EOF
	fi
done

trimfiles

rm -f /tmp/iprt.* $empty
