#! /bin/csh -f

# @(#) $Header: /Users/thomas/direwolf-libax25-agwpe/wampes-import/wampes-cvs/wampes/tools/tcpmake,v 1.3 1993/02/28 17:35:23 deyke Exp $

foreach dir (           \
	~/tcp           \
	~/tcp/bbs       \
	~/tcp/convers   \
	~/tcp/doc       \
	~/tcp/src       \
	~/tcp/src/tools \
	~/tcp/util      )
  cd $dir
  trimfiles
end
tcpremove
cd ~/tcp/src
makeall |& tee xxx
cd ~/tcp
make
mk make
