#! /bin/csh -f

# @(#) $Header: /Users/thomas/direwolf-libax25-agwpe/wampes-import/wampes-cvs/wampes/tools/tcpmake,v 1.1 1992/09/05 08:14:59 deyke Exp $

tcpremove
cd ~/tcp/src
makeall |& tee xxx
cd ..
make
mk make
